# Generated by Django 4.2.3 on 2023-07-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('working', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=15)),
            ],
        ),
    ]
