# Generated by Django 4.2.3 on 2023-07-20 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(max_length=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
