# Generated by Django 4.2.3 on 2023-07-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_testimonial_picture_alter_testimonial_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
